# package

In [1]:
#pip install openai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.6/73.6 kB 133.3 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.9/354.9 kB 287.3 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 64.7 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 98.6 kB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 23.0 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [226]:
import openai
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
import re
import string
import jieba
import jieba.analyse
from zhon.hanzi import punctuation
import opencc
from sklearn.feature_extraction.text import CountVectorizer  
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
import csv

# 測試 openai API

In [14]:
openai.api_key = "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"

In [23]:
response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": "你是誰？"},
        {"role": "user", "content": "介紹一下你的名字"}
    ]
)

response['choices'][0]['message']['content']

'我是AI智能助手，暱稱為AI小助手。'

In [29]:
type(response['choices'][0]['message']['content'])

str

In [24]:
response['usage']['total_tokens']

50

In [20]:
response

<OpenAIObject chat.completion id=chatcmpl-7Qbs6d4uZHzLoctzsnAsQkpyYNMU7 at 0x7f92d936c590> JSON: {
  "id": "chatcmpl-7Qbs6d4uZHzLoctzsnAsQkpyYNMU7",
  "object": "chat.completion",
  "created": 1686576462,
  "model": "gpt-3.5-turbo-0301",
  "usage": {
    "prompt_tokens": 13,
    "completion_tokens": 38,
    "total_tokens": 51
  },
  "choices": [
    {
      "message": {
        "role": "assistant",
        "content": "\u6211\u662f\u4e00\u500bAI\u8a9e\u8a00\u6a21\u578b\uff0c\u53ef\u4ee5\u6839\u64da\u4eba\u5011\u7684\u63d0\u554f\u6216\u6307\u4ee4\u9032\u884c\u8a08\u7b97\u548c\u56de\u7b54\u3002"
      },
      "finish_reason": "stop",
      "index": 0
    }
  ]
}

# 建立摘要文本字串與提問

In [25]:
# 摘要文本一之提問字串
abstract1 = "媒體對同一主題的報導經常有明顯差異，本文以報紙報導風格為研究目標，比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格。避免報紙立場及題材造成的干擾，本文選取每天頭版頭條新聞，資料期間為2012年至2018年，其中頭條標題涵蓋四大報，但頭條內文僅有《蘋果日報》、《自由時報》。本文分析常用詞彙、句長、標點、虛字，發現四大報頭條標題及內文的用字風格不完全相同，其中標題的Jaccard指標將同時期報導放在同一群，Yue指標將四大報分成三群；內文分析發現《自由時報》傾向政治新聞，《蘋果日報》傾向社會新聞，以能夠代表兩報的常見詞彙為解釋變數，統計及機器學習 模型都能準確地區隔《自由時報》或《蘋果日報》。\n\n上述是一篇文字分析領域的論文摘要，請幫我條列整理出研究動機、研究目的、研究方法與研究結果四大項，若無法區分其分類也請標示出來。"
print(abstract1)

媒體對同一主題的報導經常有明顯差異，本文以報紙報導風格為研究目標，比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格。避免報紙立場及題材造成的干擾，本文選取每天頭版頭條新聞，資料期間為2012年至2018年，其中頭條標題涵蓋四大報，但頭條內文僅有《蘋果日報》、《自由時報》。本文分析常用詞彙、句長、標點、虛字，發現四大報頭條標題及內文的用字風格不完全相同，其中標題的Jaccard指標將同時期報導放在同一群，Yue指標將四大報分成三群;內文分析發現《自由時報》傾向政治新聞，《蘋果日報》傾向社會新聞，以能夠代表兩報的常見詞彙為解釋變數，統計及機器學習 模型都能準確地區隔《自由時報》或《蘋果日報》。

上述是一篇文字分析領域的論文摘要，請幫我條列整理出研究動機、研究目的、研究方法與研究結果四大項，若無法區分其分類也請標示出來。


In [26]:
# 測試問第一次
response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": abstract1}
    ]
)

response['choices'][0]['message']['content']

'研究動機：\n- 媒體對同一主題的報導經常有明顯差異，欲探討不同報紙的報導風格。\n\n研究目的：\n- 比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格。\n- 探討不同報紙頭條標題及內文的用字風格。\n\n研究方法：\n- 選取每天頭版頭條新聞，資料期間為2012年至2018年。\n- 以常用詞彙、句長、標點、虛字等為分析變數，比較四大報頭條標題及內文的用字風格。\n- 使用Jaccard指標及Yue指標進行聚類分析，以區分不同報紙的風格。\n\n研究結果：\n- 四大報頭條標題及內文的用字風格不完全相同。\n- Jaccard指標將同時期報導放在同一群，Yue指標將四大報分成三群。\n- 《自由時報》傾向政治新聞，《蘋果日報》傾向社會新聞。\n- 統計及機器學習模型都能準確地區隔《自由時報》或《蘋果日報》。'

In [27]:
# 測試問第一次：用print()的結果看換行符號的呈現效果
print(response['choices'][0]['message']['content'])

研究動機：
- 媒體對同一主題的報導經常有明顯差異，欲探討不同報紙的報導風格。

研究目的：
- 比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格。
- 探討不同報紙頭條標題及內文的用字風格。

研究方法：
- 選取每天頭版頭條新聞，資料期間為2012年至2018年。
- 以常用詞彙、句長、標點、虛字等為分析變數，比較四大報頭條標題及內文的用字風格。
- 使用Jaccard指標及Yue指標進行聚類分析，以區分不同報紙的風格。

研究結果：
- 四大報頭條標題及內文的用字風格不完全相同。
- Jaccard指標將同時期報導放在同一群，Yue指標將四大報分成三群。
- 《自由時報》傾向政治新聞，《蘋果日報》傾向社會新聞。
- 統計及機器學習模型都能準確地區隔《自由時報》或《蘋果日報》。


In [28]:
# 測試問第二次：發現每次回傳的結果確實不太相同
response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": abstract1}
    ]
)

print(response['choices'][0]['message']['content'])

研究動機：
- 媒體對同一主題的報導經常有明顯差異，因此有必要深入研究不同報紙的報導風格。

研究目的：
- 比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格。
- 分析常用詞彙、句長、標點、虛字等因素，深入探討四大報頭條標題及內文的用字風格。
- 了解不同報紙報導風格的差異性，進一步探究其背後的因素。

研究方法：
- 避免報紙立場及題材造成的干擾，以每天頭版頭條新聞作為研究對象，資料期間為2012年至2018年，其中頭條標題涵蓋四大報，但頭條內文僅有《蘋果日報》、《自由時報》。
- 分析常用詞彙、句長、標點、虛字等因素，使用Jaccard指標及Yue指標進行分類分析。
- 統計及機器學習模型，以常見詞彙為解釋變數，區隔出不同報紙的報導風格。

研究結果：
- 四大報頭條標題及內文的用字風格不完全相同，其中標題的Jaccard指標將同時期報導放在同一群，Yue指標將四大報分成三群。
- 《自由時報》傾向政治新聞，《蘋果日報》傾向社會新聞。
- 統計及機器學習模型都能準確地區隔《自由時報》或《蘋果日報》。


# 蒐集模擬提問100次的結果

In [33]:
# 空dataframe
df = pd.DataFrame()
df["id"] = list(range(1,101))
df["response"] = [np.nan]*100
df

id  response
0     1       NaN
1     2       NaN
2     3       NaN
3     4       NaN
4     5       NaN
..  ...       ...
95   96       NaN
96   97       NaN
97   98       NaN
98   99       NaN
99  100       NaN

[100 rows x 2 columns]

In [36]:
# testing
df["response"][1] = response['choices'][0]['message']['content']
df

id                                           response
0     1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，因此有必要深入研究不同報紙的報導風格。...
1     2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，因此有必要深入研究不同報紙的報導風格。...
2     3                                                NaN
3     4                                                NaN
4     5                                                NaN
..  ...                                                ...
95   96                                                NaN
96   97                                                NaN
97   98                                                NaN
98   99                                                NaN
99  100                                                NaN

[100 rows x 2 columns]

In [37]:
for i in tqdm(range(100)):
    response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": abstract1}
    ]
    )
    df["response"][i] = response['choices'][0]['message']['content']
    df.to_csv(("response.csv"), index=False, encoding="utf-8")

# 整理一則回覆訊息

In [34]:
one = pd.read_csv("response.csv")
two = pd.read_csv("response2.csv")
response_df = pd.concat([one,two],ignore_index=True)
response_df

id                                           response
0      1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...
1      2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...
2      3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...
3      4  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，希望透過研究報紙報導風格，了解不同媒體...
4      5  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，因此探討報紙報導風格的差異性。\n\n...
..   ...                                                ...
195  196  研究動機：\n- 媒體報導同一主題時，報導風格經常有明顯差異，研究探討報紙報導風格。\n\n...
196  197  研究動機：\n- 媒體對同一主題的報導經常有明顯差異\n\n研究目的：\n- 比較臺灣四大報...
197  198  研究動機：\n- 媒體對同一主題的報導存在差異，想探討不同報紙的報導風格。\n\n研究目的：...
198  199  研究動機：\n- 媒體對同一主題報導風格的差異常有明顯差異，想研究台灣四大報的報導風格。\n...
199  200  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，想要進一步探討報紙報導風格差異的原因。...

[200 rows x 2 columns]

In [35]:
# 沒有完全相同的回覆
len(response_df["response"].drop_duplicates())

200

In [36]:
"1. " in response_df["response"][55]

False

In [37]:
# 判別回覆屬於條列式、數字條列、敘述
response_df["type"] = response_df["response"].transform(lambda x: "point" if "- " in x else("num" if "1. " in x else "none"))

response_df

id                                           response   type
0      1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...  point
1      2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...  point
2      3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...  point
3      4  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，希望透過研究報紙報導風格，了解不同媒體...  point
4      5  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，因此探討報紙報導風格的差異性。\n\n...  point
..   ...                                                ...    ...
195  196  研究動機：\n- 媒體報導同一主題時，報導風格經常有明顯差異，研究探討報紙報導風格。\n\n...  point
196  197  研究動機：\n- 媒體對同一主題的報導經常有明顯差異\n\n研究目的：\n- 比較臺灣四大報...  point
197  198  研究動機：\n- 媒體對同一主題的報導存在差異，想探討不同報紙的報導風格。\n\n研究目的：...  point
198  199  研究動機：\n- 媒體對同一主題報導風格的差異常有明顯差異，想研究台灣四大報的報導風格。\n...  point
199  200  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，想要進一步探討報紙報導風格差異的原因。...  point

[200 rows x 3 columns]

In [38]:
# 組織方式
response_df.type.value_counts()

point    163
none      25
num       12
Name: type, dtype: int64

In [13]:
print(response_df["response"][0])

研究動機：
- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？

研究目的：
- 比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格，以報紙報導風格為研究目標。
- 避免報紙立場及題材造成的干擾，本文選取每天頭版頭條新聞。資料期間為2012年至2018年，其中頭條標題涵蓋四大報，但頭條內文僅有《蘋果日報》、《自由時報》。
- 本文分析常用詞彙、句長、標點、虛字等關鍵詞元素，探討不同報紙在報導風格上的差異。

研究方法：
- 文字分析法：從詞彙、句長、標點、虛字等角度進行分析。
- 統計分析法：將四大報頭條標題及內文分成不同群，進行比較分析。
- 機器學習模型：使用統計及機器學習模型來區隔《自由時報》或《蘋果日報》。

研究結果：
- 四大報頭條標題及內文的用字風格不完全相同，其中標題的Jaccard指標將同時期報導放在同一群，Yue指標將四大報分成三群。
- 內文分析發現《自由時報》傾向政治新聞，《蘋果日報》傾向社會新聞，以能夠代表兩報的常見詞彙為解釋變數，統計及機器學習模型都能準確地區隔《自由時報》或《蘋果日報》。


In [22]:
# 斷句
sentence_list = list(filter(None, re.split(r'[。|！|？|；|\n]\s*', response_df["response"][0])))
sentence_list

['研究動機：',
 '- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異',
 '研究目的：',
 '- 比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格，以報紙報導風格為研究目標',
 '- 避免報紙立場及題材造成的干擾，本文選取每天頭版頭條新聞',
 '資料期間為2012年至2018年，其中頭條標題涵蓋四大報，但頭條內文僅有《蘋果日報》、《自由時報》',
 '- 本文分析常用詞彙、句長、標點、虛字等關鍵詞元素，探討不同報紙在報導風格上的差異',
 '研究方法：',
 '- 文字分析法：從詞彙、句長、標點、虛字等角度進行分析',
 '- 統計分析法：將四大報頭條標題及內文分成不同群，進行比較分析',
 '- 機器學習模型：使用統計及機器學習模型來區隔《自由時報》或《蘋果日報》',
 '研究結果：',
 '- 四大報頭條標題及內文的用字風格不完全相同，其中標題的Jaccard指標將同時期報導放在同一群，Yue指標將四大報分成三群',
 '- 內文分析發現《自由時報》傾向政治新聞，《蘋果日報》傾向社會新聞，以能夠代表兩報的常見詞彙為解釋變數，統計及機器學習模型都能準確地區隔《自由時報》或《蘋果日報》']

In [23]:
# 總句數
num_sentence = len(sentence_list)
num_sentence

14

In [25]:
# 去除條列符號
long = "。".join(sentence_list).replace("- ","").replace("1. ","").replace("2. ","").replace("3. ","").replace("4. ","")
long

'研究動機：。媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異。研究目的：。比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格，以報紙報導風格為研究目標。避免報紙立場及題材造成的干擾，本文選取每天頭版頭條新聞。資料期間為2012年至2018年，其中頭條標題涵蓋四大報，但頭條內文僅有《蘋果日報》、《自由時報》。本文分析常用詞彙、句長、標點、虛字等關鍵詞元素，探討不同報紙在報導風格上的差異。研究方法：。文字分析法：從詞彙、句長、標點、虛字等角度進行分析。統計分析法：將四大報頭條標題及內文分成不同群，進行比較分析。機器學習模型：使用統計及機器學習模型來區隔《自由時報》或《蘋果日報》。研究結果：。四大報頭條標題及內文的用字風格不完全相同，其中標題的Jaccard指標將同時期報導放在同一群，Yue指標將四大報分成三群。內文分析發現《自由時報》傾向政治新聞，《蘋果日報》傾向社會新聞，以能夠代表兩報的常見詞彙為解釋變數，統計及機器學習模型都能準確地區隔《自由時報》或《蘋果日報》'

In [30]:
# 斷詞與設定

# 簡體轉換成繁體中文
converter = opencc.OpenCC("s2t.json")
# 輸入簡體字停用詞list並轉換為繁體中文
cn_stopwords=pd.read_csv("/Users/liuchenli/CodeStuff/cn_stopwords.txt")
cn_stopwords_trans = []
for i in cn_stopwords.iloc[0:len(cn_stopwords),0]:
    cn_stopwords_trans.append(converter.convert(i))
# 設定字典
jieba.set_dictionary("/Users/liuchenli/CodeStuff/dict_wo_l_nr_i.txt")
# 斷詞
print(long)
word_cut = jieba.lcut(long)
words = str()
length = 0
for word in word_cut:
    if word not in punctuation:
        length += len(word) # 總字數(不包含標點符號)
    if word not in cn_stopwords_trans:
        words = words+str(word)+" "

print(words)
print(length)

Building prefix dict from /Users/liuchenli/CodeStuff/dict_wo_l_nr_i.txt ...
Loading model from cache /var/folders/dd/s_mrgqnx0cvff0cmsg_vwxjc0000gp/T/jieba.uc5fb58e83c89c4f88f91cd2c50a62ef0.cache


研究動機：。媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異。研究目的：。比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格，以報紙報導風格為研究目標。避免報紙立場及題材造成的干擾，本文選取每天頭版頭條新聞。資料期間為2012年至2018年，其中頭條標題涵蓋四大報，但頭條內文僅有《蘋果日報》、《自由時報》。本文分析常用詞彙、句長、標點、虛字等關鍵詞元素，探討不同報紙在報導風格上的差異。研究方法：。文字分析法：從詞彙、句長、標點、虛字等角度進行分析。統計分析法：將四大報頭條標題及內文分成不同群，進行比較分析。機器學習模型：使用統計及機器學習模型來區隔《自由時報》或《蘋果日報》。研究結果：。四大報頭條標題及內文的用字風格不完全相同，其中標題的Jaccard指標將同時期報導放在同一群，Yue指標將四大報分成三群。內文分析發現《自由時報》傾向政治新聞，《蘋果日報》傾向社會新聞，以能夠代表兩報的常見詞彙為解釋變數，統計及機器學習模型都能準確地區隔《自由時報》或《蘋果日報》


Loading model cost 1.435 seconds.
Prefix dict has been built successfully.


研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 自由時報 聯合報 中國時報 報導 風格 報紙 報導 風格 為 研究 目標 避免 報紙 立場 題材 造成 干擾 本文 選取 每天 頭版頭條 新聞 資料 期間 為 2012 年 2018 年 頭條 標題 涵蓋 四大報 頭條 內文 僅有 蘋果日報 自由時報 本文 分析 常用 詞彙 句長 標點 虛字 關鍵詞 元素 探討 不同 報紙 報導 風格 差異 研究方法 文字 分析法 詞彙 句長 標點 虛字 角度 進行 分析 統計 分析法 四大報 頭條 標題 內文 分成 不同 群 進行 比較 分析 機器 學習 模型 使用 統計 機器 學習 模型 區隔 自由時報 蘋果日報 研究結果 四大報 頭條 標題 內文 用字 風格 完全 相同 標題 Jaccard 指標 將同 時期 報導 放在 一群 Yue 指標 四大報 分成 三群 內文 分析 發現 自由時報 傾向 政治 新聞 蘋果日報 傾向 社會 新聞 能夠 代表 兩報 常見 詞彙 為 解釋 變數 統計 機器 學習 模型 準確 地區 隔 自由時報 蘋果日報 
394


In [31]:
# 詞數
num_word = len(words.split())
num_word

156

# 整理全部回覆訊息

In [123]:
# 簡體轉換成繁體中文
converter = opencc.OpenCC("s2t.json")
# 輸入簡體字停用詞list並轉換為繁體中文
cn_stopwords=pd.read_csv("/Users/liuchenli/CodeStuff/cn_stopwords.txt")
cn_stopwords_trans = []
for i in cn_stopwords.iloc[0:len(cn_stopwords),0]:
    cn_stopwords_trans.append(converter.convert(i))
# 設定字典
jieba.set_dictionary("/Users/liuchenli/CodeStuff/dict_wo_l_nr_i.txt")

In [124]:
length_list = []
num_sentence = []
words_cut = []
num_word = []

for i in range(200):
    # 斷句
    sentence_list = list(filter(None, re.split(r'[。|！|？|；|\n]\s*', response_df["response"][i])))
    # 總句數
    num_sentence.append(len(sentence_list))
    # 去除條列符號
    long = "。".join(sentence_list).replace("- ","").replace("1. ","").replace("2. ","").replace("3. ","").replace("4. ","")
    # 斷詞
    word_cut = jieba.lcut(converter.convert(long))
    words = str()
    length = 0
    for word in word_cut:
        if word not in punctuation:
            length += len(word) # 總字數(不包含標點符號)
        if word not in cn_stopwords_trans:
            words = words+str(word)+" "
    words_cut.append(words)
    length_list.append(length)
    # 詞數
    num_word.append(len(words.split()))

response_df["length"] = length_list
response_df["num_sentence"] = num_sentence
response_df["num_word"] = num_word
response_df["words_cut"] = words_cut

response_df

Building prefix dict from /Users/liuchenli/CodeStuff/dict_wo_l_nr_i.txt ...
Dumping model to file cache /var/folders/dd/s_mrgqnx0cvff0cmsg_vwxjc0000gp/T/jieba.uc5fb58e83c89c4f88f91cd2c50a62ef0.cache
Loading model cost 1.764 seconds.
Prefix dict has been built successfully.


id                                           response   type  length  \
0      1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...  point     394   
1      2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...  point     388   
2      3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...  point     309   
3      4  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，希望透過研究報紙報導風格，了解不同媒體...  point     377   
4      5  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，因此探討報紙報導風格的差異性。\n\n...  point     341   
..   ...                                                ...    ...     ...   
195  196  研究動機：\n- 媒體報導同一主題時，報導風格經常有明顯差異，研究探討報紙報導風格。\n\n...  point     396   
196  197  研究動機：\n- 媒體對同一主題的報導經常有明顯差異\n\n研究目的：\n- 比較臺灣四大報...  point     301   
197  198  研究動機：\n- 媒體對同一主題的報導存在差異，想探討不同報紙的報導風格。\n\n研究目的：...  point     278   
198  199  研究動機：\n- 媒體對同一主題報導風格的差異常有明顯差異，想研究台灣四大報的報導風格。\n...  point     292   
199  200  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，想要進一步探討報紙報導風格差異的原因。...  point     403   

     num_sentence  num_word                                          words_cut  
0              14       157  研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異...  
1              17       153  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究 探討 報紙 報導 風格 差異 研究...  
2              15       121  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...  
3              14       149  研究動機 媒體 同一 主題 報導 經常 明顯 差異 希望 透過 研究 報紙 報導 風格 瞭解...  
4              16       138  研究動機 媒體 同一 主題 報導 經常 明顯 差異 探討 報紙 報導 風格 差異 性 研究目...  
..            ...       ...                                                ...  
195            15       163  研究動機 媒體 報導 同一 主題 時 報導 風格 經常 明顯 差異 研究 探討 報紙 報導 ...  
196            15       117  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...  
197            13       110  研究動機 媒體 同一 主題 報導 存在 差異 想 探討 不同 報紙 報導 風格 研究目的 比...  
198            14       115  研究動機 媒體 同一 主題 報導 風格 差異 常有 明顯 差異 想 研究 臺灣 四大報 報導...  
199            15       160  研究動機 媒體 同一 主題 報導 經常 明顯 差異 想要 進一步 探討 報紙 報導 風格 差...  

[200 rows x 7 columns]

In [126]:
response_df.to_csv(("response_df.csv"), index=False, encoding="utf-8")

# 研究結果

## 回覆結構差異

In [248]:
# 原文本統計量
abstract = "媒體對同一主題的報導經常有明顯差異，本文以報紙報導風格為研究目標，比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格。避免報紙立場及題材造成的干擾，本文選取每天頭版頭條新聞，資料期間為2012年至2018年，其中頭條標題涵蓋四大報，但頭條內文僅有《蘋果日報》、《自由時報》。本文分析常用詞彙、句長、標點、虛字，發現四大報頭條標題及內文的用字風格不完全相同，其中標題的Jaccard指標將同時期報導放在同一群，Yue指標將四大報分成三群；內文分析發現《自由時報》傾向政治新聞，《蘋果日報》傾向社會新聞，以能夠代表兩報的常見詞彙為解釋變數，統計及機器學習 模型都能準確地區隔《自由時報》或《蘋果日報》。"

# 斷句
sentence_list = list(filter(None, re.split(r'[。|！|？|；|\n]\s*', abstract)))

# 總句數
num_sentence = len(sentence_list)
print(num_sentence)

# 去除條列符號
long = "。".join(sentence_list).replace("- ","").replace("1. ","").replace("2. ","").replace("3. ","").replace("4. ","")

# 斷詞
word_cut = jieba.lcut(long)
words = str()
length = 0
for word in word_cut:
    if word not in punctuation:
        length += len(word) # 總字數(不包含標點符號)
    if word not in cn_stopwords_trans:
        words = words+str(word)+" "

print(length)

# 詞數
num_word = len(words.split())
print(num_word)

4
269
107


In [103]:
# 組織方式
response_df.type.value_counts()

point    163
none      25
num       12
Name: type, dtype: int64

In [127]:
# 字數、句數、詞數
response_df.describe()

id      length  num_sentence    num_word
count  200.000000  200.000000    200.000000  200.000000
mean   100.500000  339.930000     13.900000  133.770000
std     57.879185   45.400342      2.534188   18.027815
min      1.000000  205.000000      4.000000   79.000000
25%     50.750000  309.000000     13.000000  121.000000
50%    100.500000  339.000000     14.000000  133.500000
75%    150.250000  366.000000     15.000000  145.000000
max    200.000000  492.000000     20.000000  195.000000

In [247]:
response_df.describe().to_csv("response_df_describe.csv", index=False, encoding="utf-8")

## 重要詞彙差異

In [135]:
corpus = list(response_df["words_cut"])
corpus[:5]

['研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 自由時報 聯合報 中國時報 報導 風格 報紙 報導 風格 為 研究 目標 避免 報紙 立場 題材 造成 幹擾 本文 選取 每天 頭版頭條 新聞 資料 期間 為 2012 年 2018 年 頭條 標題 涵蓋 四大報 頭條 內文 僅有 蘋果日報 自由時報 本文 分析 常用 詞彙 句長 標點 虛字 關鍵詞 元素 探討 不同 報紙 報導 風格 差異 研究方法 文字 分析法 詞彙 句長 標點 虛字 角度 進行 分析 統計 分析法 四大報 頭條 標題 內文 分成 不同 羣 進行 比較 分析 機器 學習 模型 使用 統計 機器 學習 模型 區隔 自由時報 蘋果日報 研究結果 四大報 頭條 標題 內文 用字 風格 完全 相同 標題 Jaccard 指標 將同 時期 報導 放在 一羣 Yue 指標 四大報 分成 三 羣 內文 分析 發現 自由時報 傾向 政治 新聞 蘋果日報 傾向 社會 新聞 能夠 代表 兩報 常見 詞彙 為 解釋 變數 統計 機器 學習 模型 準確 地區 隔 自由時報 蘋果日報 ',
 '研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究 探討 報紙 報導 風格 差異 研究目的 比較 臺灣 四大報 蘋果日報 自由時報 聯合報 中國時報 報導 風格 評估 報紙 頭條 標題 內文 口吻 風格 不同 探索 各報 主題 相似 新聞報導 差異 評估 常用 詞彙 句長 標點 虛字 因素 各報 風格 影響 研究方法 選取 每日 頭版頭條 新聞 範圍 為 2012 年 2018 年 濾除 報紙 立場 題材 影響 常用 詞彙 句長 標點 虛字 因素 作為 解釋 變數 分析 各報 標題 內文 用字 風格 使用   Jaccard 指標   Yue 指標 比較 報紙 標題 之間 相似 度 區分 報社 風格 不同 統計 機器 學習 模型 評估 常用 詞彙 各報 風格 影響 進行 區隔 研究結果 四大報 頭條 標題 內文 用字 風格 完全 相同 標題 Jaccard 指標 將同 時期 報導 放在 一羣 Yue 指標 四大報 分成 三 羣 報紙 內文 分析 發現 自由時報 傾向 政治 新聞 蘋果日報 傾向 社會 新聞 統計 機器 學習 分析 使用 常見

In [136]:
#将文本中的词语转换为词频矩阵  
vectorizer = CountVectorizer(stop_words=None)  
#计算个词语出现的次数  
X = vectorizer.fit_transform(corpus)  
#获取词袋中所有文本关键词  
word = vectorizer.get_feature_names()  
#查看词频结果  
df_word =  pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names())
df_word['Col_sum'] = df_word.apply(lambda x: x.sum(), axis=1)

df_word

2012  2018  21916  6943  jaccard  mining  texto  yue  一個  一定  ...  類別  \
0       1     1      0     0        1       0      0    1   0   0  ...   0   
1       1     1      0     0        2       0      0    2   0   0  ...   0   
2       1     1      0     0        2       0      0    2   0   0  ...   0   
3       1     1      0     0        2       0      0    2   0   0  ...   0   
4       1     1      0     0        2       0      0    2   0   0  ...   0   
..    ...   ...    ...   ...      ...     ...    ...  ...  ..  ..  ...  ..   
195     2     2      0     0        2       0      0    2   0   0  ...   0   
196     1     1      0     0        2       0      0    2   0   0  ...   0   
197     1     1      0     0        2       0      0    2   0   0  ...   0   
198     1     1      0     0        2       0      0    2   0   0  ...   0   
199     1     1      0     0        2       0      0    2   0   0  ...   0   

     類型  顯示  顯著  顯著性  風格  風格特徵  驗證  點與  Col_sum  
0     0   0   0    0   5     0   0   0      148  
1     0   0   0    0   8     0   0   0      146  
2     0   0   0    0   4     0   0   0      112  
3     1   0   0    0   8     0   0   0      142  
4     0   0   0    0   7     0   0   0      128  
..   ..  ..  ..  ...  ..   ...  ..  ..      ...  
195   0   0   0    0   5     0   0   0      148  
196   0   0   0    0   3     0   0   0      110  
197   0   0   0    0   5     0   0   0      100  
198   0   0   0    0   6     0   0   0      105  
199   0   0   0    0   5     0   0   0      152  

[200 rows x 426 columns]

In [137]:
df_word.to_csv(("df_word.csv"), index=False, encoding="utf-8")

### 由詞頻選關鍵詞

In [175]:
# 所有文本中詞頻top 10
df_word.apply(lambda x: x.sum(), axis=0).sort_values(ascending=False)[1:11]

報導      1114
風格      1046
四大報      912
指標       771
蘋果日報     751
自由時報     751
分析       665
新聞       648
標題       609
詞彙       549
dtype: int64

In [176]:
tf_top_10 = list(df_word.apply(lambda x: x.sum(), axis=0).sort_values(ascending=False).index[1:11])
tf_top_10

['報導', '風格', '四大報', '指標', '蘋果日報', '自由時報', '分析', '新聞', '標題', '詞彙']

In [151]:
# 各篇文本中詞頻top 10
df_word.iloc[0].sort_values(ascending=False)[1:11]

報導      6
風格      5
四大報     5
自由時報    5
蘋果日報    5
內文      4
頭條      4
分析      4
報紙      4
標題      4
Name: 0, dtype: int64

In [148]:
list(df_word.iloc[1].sort_values(ascending=False).index[1:11])

['風格', '標題', '報紙', '指標', '內文', '各報', '詞彙', '報導', '蘋果日報', '影響']

In [154]:
",".join(list(df_word.iloc[1].sort_values(ascending=False).index[1:11]))

'風格,標題,報紙,指標,內文,各報,詞彙,報導,蘋果日報,影響'

In [159]:
tf_key = []
for i in range(200):
    i_tf_key_list = list(df_word.iloc[i].sort_values(ascending=False).index[1:11])
    tf_key.append(",".join(i_tf_key_list))

response_df["tf_key"] = tf_key
response_df

id                                           response   type  length  \
0      1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...  point     394   
1      2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...  point     388   
2      3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...  point     309   
3      4  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，希望透過研究報紙報導風格，了解不同媒體...  point     377   
4      5  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，因此探討報紙報導風格的差異性。\n\n...  point     341   
..   ...                                                ...    ...     ...   
195  196  研究動機：\n- 媒體報導同一主題時，報導風格經常有明顯差異，研究探討報紙報導風格。\n\n...  point     396   
196  197  研究動機：\n- 媒體對同一主題的報導經常有明顯差異\n\n研究目的：\n- 比較臺灣四大報...  point     301   
197  198  研究動機：\n- 媒體對同一主題的報導存在差異，想探討不同報紙的報導風格。\n\n研究目的：...  point     278   
198  199  研究動機：\n- 媒體對同一主題報導風格的差異常有明顯差異，想研究台灣四大報的報導風格。\n...  point     292   
199  200  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，想要進一步探討報紙報導風格差異的原因。...  point     403   

     num_sentence  num_word  \
0              14       157   
1              17       153   
2              15       121   
3              14       149   
4              16       138   
..            ...       ...   
195            15       163   
196            15       117   
197            13       110   
198            14       115   
199            15       160   

                                             words_cut  \
0    研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異...   
1    研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究 探討 報紙 報導 風格 差異 研究...   
2    研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...   
3    研究動機 媒體 同一 主題 報導 經常 明顯 差異 希望 透過 研究 報紙 報導 風格 瞭解...   
4    研究動機 媒體 同一 主題 報導 經常 明顯 差異 探討 報紙 報導 風格 差異 性 研究目...   
..                                                 ...   
195  研究動機 媒體 報導 同一 主題 時 報導 風格 經常 明顯 差異 研究 探討 報紙 報導 ...   
196  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...   
197  研究動機 媒體 同一 主題 報導 存在 差異 想 探討 不同 報紙 報導 風格 研究目的 比...   
198  研究動機 媒體 同一 主題 報導 風格 差異 常有 明顯 差異 想 研究 臺灣 四大報 報導...   
199  研究動機 媒體 同一 主題 報導 經常 明顯 差異 想要 進一步 探討 報紙 報導 風格 差...   

                                 tf_key  
0    報導,風格,四大報,自由時報,蘋果日報,內文,頭條,分析,報紙,標題  
1       風格,標題,報紙,指標,內文,各報,詞彙,報導,蘋果日報,影響  
2    報導,四大報,風格,指標,詞彙,區分,報紙,蘋果日報,標題,自由時報  
3    報導,風格,不同,分析,四大報,自由時報,新聞,蘋果日報,指標,詞彙  
4    報導,風格,四大報,分析,差異,指標,頭條,蘋果日報,新聞,自由時報  
..                                  ...  
195  四大報,報導,風格,蘋果日報,指標,新聞,自由時報,標題,詞彙,內文  
196  蘋果日報,指標,自由時報,分析,新聞,標題,風格,內文,四大報,報導  
197  報導,風格,四大報,指標,蘋果日報,新聞,自由時報,分析,進行,比較  
198  風格,報導,四大報,蘋果日報,指標,自由時報,新聞,分析,詞彙,研究  
199  四大報,分析,自由時報,蘋果日報,報導,標題,風格,內文,指標,頭條  

[200 rows x 8 columns]

In [177]:
# one-hot empty
count_df = pd.DataFrame(columns = tf_top_10, index = range(len(response_df)))
count_df["id"] = response_df["id"]
response_df_tf_key = response_df.merge(count_df, on=["id"], how="left")
response_df_tf_key.head(3)

id                                           response   type  length  \
0   1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...  point     394   
1   2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...  point     388   
2   3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...  point     309   

   num_sentence  num_word                                          words_cut  \
0            14       157  研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異...   
1            17       153  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究 探討 報紙 報導 風格 差異 研究...   
2            15       121  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...   

                               tf_key   報導   風格  四大報   指標 蘋果日報 自由時報   分析   新聞  \
0  報導,風格,四大報,自由時報,蘋果日報,內文,頭條,分析,報紙,標題  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1     風格,標題,報紙,指標,內文,各報,詞彙,報導,蘋果日報,影響  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2  報導,四大報,風格,指標,詞彙,區分,報紙,蘋果日報,標題,自由時報  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

    標題   詞彙  
0  NaN  NaN  
1  NaN  NaN  
2  NaN  NaN

In [179]:
mapping

{'報導': 0,
 '風格': 1,
 '四大報': 2,
 '指標': 3,
 '蘋果日報': 4,
 '自由時報': 5,
 '分析': 6,
 '新聞': 7,
 '標題': 8,
 '詞彙': 9}

In [181]:
mapping = {}
for x in range(len(tf_top_10)):
  mapping[tf_top_10[x]] = x

for i in range(len(response_df_tf_key)):

  arr = list(np.zeros(len(tf_top_10), dtype = int))
  i_split = re.split(r'[,]', response_df_tf_key["tf_key"][i])
  for unit in i_split:
    if unit in tf_top_10:
      arr[mapping[unit]] += 1

  response_df_tf_key.iloc[i,8:18] = arr

response_df_tf_key.head(3)

id                                           response   type  length  \
0   1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...  point     394   
1   2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...  point     388   
2   3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...  point     309   

   num_sentence  num_word                                          words_cut  \
0            14       157  研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異...   
1            17       153  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究 探討 報紙 報導 風格 差異 研究...   
2            15       121  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...   

                               tf_key 報導 風格 四大報 指標 蘋果日報 自由時報 分析 新聞 標題 詞彙  
0  報導,風格,四大報,自由時報,蘋果日報,內文,頭條,分析,報紙,標題  1  1   1  0    1    1  1  0  1  0  
1     風格,標題,報紙,指標,內文,各報,詞彙,報導,蘋果日報,影響  1  1   0  1    1    0  0  0  1  1  
2  報導,四大報,風格,指標,詞彙,區分,報紙,蘋果日報,標題,自由時報  1  1   1  1    1    1  0  0  1  1

In [185]:
# 全部詞頻top 10中，每個文本有包含的總數（最多200）
response_df_tf_key.iloc[:,8:18].apply(lambda x: x.sum(), axis=0)

報導      198
風格      191
四大報     191
指標      176
蘋果日報    168
自由時報    161
分析      107
新聞      144
標題      114
詞彙       78
dtype: int64

In [188]:
# 每個文本有包含幾個全部詞頻top 10
response_df_tf_key["contain"] = response_df_tf_key.iloc[:,8:18].apply(lambda x: x.sum(), axis=1)
response_df_tf_key.head(3)

id                                           response   type  length  \
0   1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...  point     394   
1   2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...  point     388   
2   3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...  point     309   

   num_sentence  num_word                                          words_cut  \
0            14       157  研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異...   
1            17       153  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究 探討 報紙 報導 風格 差異 研究...   
2            15       121  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...   

                               tf_key 報導 風格 四大報 指標 蘋果日報 自由時報 分析 新聞 標題 詞彙  \
0  報導,風格,四大報,自由時報,蘋果日報,內文,頭條,分析,報紙,標題  1  1   1  0    1    1  1  0  1  0   
1     風格,標題,報紙,指標,內文,各報,詞彙,報導,蘋果日報,影響  1  1   0  1    1    0  0  0  1  1   
2  報導,四大報,風格,指標,詞彙,區分,報紙,蘋果日報,標題,自由時報  1  1   1  1    1    1  0  0  1  1   

   contain  
0        7  
1        6  
2        8

In [190]:
response_df_tf_key["contain"].describe()

count    200.0000
mean       7.6400
std        1.1476
min        4.0000
25%        7.0000
50%        8.0000
75%        8.0000
max       10.0000
Name: contain, dtype: float64

In [191]:
response_df_tf_key.to_csv(("response_df_tf_key.csv"), index=False, encoding="utf-8")

### 由TF-IDF找關鍵字

In [250]:
# 所有文本中tfidf top 10
tfidf_top_10 = jieba.analyse.extract_tags(" ".join(response_df["words_cut"]), topK = 10, withWeight = True)
tfidf_top_10

[('報導', 0.5326618269830653),
 ('風格', 0.500147460524494),
 ('四大報', 0.43607503250319174),
 ('指標', 0.3686555373464483),
 ('蘋果日報', 0.3590924883880449),
 ('自由時報', 0.3590924883880449),
 ('新聞', 0.3098427862522678),
 ('標題', 0.2911948407833813),
 ('詞彙', 0.26250569390817136),
 ('差異', 0.24768296802264617)]

In [197]:
# 各篇文本中tfidf top 10
tfidf_key = []
for i in range(200):
    i_tfidf_key_list = jieba.analyse.extract_tags(response_df["words_cut"][i], topK = 10)
    tfidf_key.append(",".join(i_tfidf_key_list))

response_df["tfidf_key"] = tfidf_key
response_df.head(3)

id                                           response   type  length  \
0   1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...  point     394   
1   2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...  point     388   
2   3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...  point     309   

   num_sentence  num_word                                          words_cut  \
0            14       157  研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異...   
1            17       153  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究 探討 報紙 報導 風格 差異 研究...   
2            15       121  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...   

                               tf_key                           tfidf_key  
0  報導,風格,四大報,自由時報,蘋果日報,內文,頭條,分析,報紙,標題  報導,風格,四大報,蘋果日報,自由時報,報紙,頭條,標題,內文,差異  
1     風格,標題,報紙,指標,內文,各報,詞彙,報導,蘋果日報,影響      風格,報紙,標題,報導,內文,各報,詞彙,指標,差異,四大報  
2  報導,四大報,風格,指標,詞彙,區分,報紙,蘋果日報,標題,自由時報  報導,四大報,風格,指標,蘋果日報,自由時報,報紙,詞彙,標題,區分

In [209]:
# one-hot empty
count_df = pd.DataFrame(columns = tfidf_top_10, index = range(len(response_df)))
count_df["id"] = response_df["id"]
response_df_tfidf_key = response_df.iloc[:,[0,1,2,3,4,5,6,8]].merge(count_df, on=["id"], how="left")
response_df_tfidf_key.head(3)

id                                           response   type  length  \
0   1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...  point     394   
1   2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...  point     388   
2   3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...  point     309   

   num_sentence  num_word                                          words_cut  \
0            14       157  研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異...   
1            17       153  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究 探討 報紙 報導 風格 差異 研究...   
2            15       121  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...   

                            tfidf_key   報導   風格  四大報   指標 蘋果日報 自由時報   新聞   標題  \
0  報導,風格,四大報,蘋果日報,自由時報,報紙,頭條,標題,內文,差異  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1      風格,報紙,標題,報導,內文,各報,詞彙,指標,差異,四大報  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2  報導,四大報,風格,指標,蘋果日報,自由時報,報紙,詞彙,標題,區分  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

    詞彙   差異  
0  NaN  NaN  
1  NaN  NaN  
2  NaN  NaN

In [210]:
mapping = {}
for x in range(len(tfidf_top_10)):
  mapping[tfidf_top_10[x]] = x

for i in range(len(response_df_tfidf_key)):

  arr = list(np.zeros(len(tfidf_top_10), dtype = int))
  i_split = re.split(r'[,]', response_df_tfidf_key["tfidf_key"][i])
  for unit in i_split:
    if unit in tfidf_top_10:
      arr[mapping[unit]] += 1

  response_df_tfidf_key.iloc[i,8:18] = arr

response_df_tfidf_key.head(3)

id                                           response   type  length  \
0   1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...  point     394   
1   2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...  point     388   
2   3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...  point     309   

   num_sentence  num_word                                          words_cut  \
0            14       157  研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異...   
1            17       153  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究 探討 報紙 報導 風格 差異 研究...   
2            15       121  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...   

                            tfidf_key 報導 風格 四大報 指標 蘋果日報 自由時報 新聞 標題 詞彙 差異  
0  報導,風格,四大報,蘋果日報,自由時報,報紙,頭條,標題,內文,差異  1  1   1  0    1    1  0  1  0  1  
1      風格,報紙,標題,報導,內文,各報,詞彙,指標,差異,四大報  1  1   1  1    0    0  0  1  1  1  
2  報導,四大報,風格,指標,蘋果日報,自由時報,報紙,詞彙,標題,區分  1  1   1  1    1    1  0  1  1  0

In [211]:
# 全部tfidf top 10中，每個文本有包含的總數（最多200）
response_df_tfidf_key.iloc[:,8:18].apply(lambda x: x.sum(), axis=0)

報導      200
風格      200
四大報     198
指標      171
蘋果日報    185
自由時報    182
新聞      131
標題      112
詞彙      106
差異      113
dtype: int64

In [212]:
# 每個文本有包含幾個全部tfidf top 10
response_df_tfidf_key["contain"] = response_df_tfidf_key.iloc[:,8:18].apply(lambda x: x.sum(), axis=1)
response_df_tfidf_key.head(3)

id                                           response   type  length  \
0   1  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？\n...  point     394   
1   2  研究動機：\n- 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。\n\n...  point     388   
2   3  研究動機：\n- 媒體對同一主題的報導經常有明顯差異。\n\n研究目的：\n- 比較臺灣四大...  point     309   

   num_sentence  num_word                                          words_cut  \
0            14       157  研究動機 媒體 同一 主題 報導 經常 明顯 差異 不同 報紙 報導 風格 是否 明顯 差異...   
1            17       153  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究 探討 報紙 報導 風格 差異 研究...   
2            15       121  研究動機 媒體 同一 主題 報導 經常 明顯 差異 研究目的 比較 臺灣 四大報 蘋果日報 ...   

                            tfidf_key 報導 風格 四大報 指標 蘋果日報 自由時報 新聞 標題 詞彙 差異  \
0  報導,風格,四大報,蘋果日報,自由時報,報紙,頭條,標題,內文,差異  1  1   1  0    1    1  0  1  0  1   
1      風格,報紙,標題,報導,內文,各報,詞彙,指標,差異,四大報  1  1   1  1    0    0  0  1  1  1   
2  報導,四大報,風格,指標,蘋果日報,自由時報,報紙,詞彙,標題,區分  1  1   1  1    1    1  0  1  1  0   

   contain  
0        7  
1        7  
2        8

In [213]:
response_df_tfidf_key["contain"].describe()

count    200.00000
mean       7.99000
std        0.95628
min        4.00000
25%        7.00000
50%        8.00000
75%        9.00000
max       10.00000
Name: contain, dtype: float64

In [214]:
response_df_tfidf_key.to_csv(("response_df_tfidf_key.csv"), index=False, encoding="utf-8")

## 文本內容相似性

In [215]:
# source: https://cloud.tencent.com/developer/article/1800081
#类调用  
transformer = TfidfTransformer(smooth_idf=True,norm='l2',use_idf=True)  
print(transformer)
#将计算好的词频矩阵X统计成TF-IDF值  
tfidf = transformer.fit_transform(X)  
#查看计算的tf-idf
df_word_tfidf = pd.DataFrame(tfidf.toarray(),columns=vectorizer.get_feature_names())
#df_word_tfidf['Col_sum'] = df_word_tfidf.apply(lambda x: x.pow(2).sum(), axis=1)

df_word_tfidf

TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)


2012      2018  21916  6943   jaccard  mining  texto       yue   一個  \
0    0.039222  0.039222    0.0   0.0  0.036399     0.0    0.0  0.036399  0.0   
1    0.032797  0.032797    0.0   0.0  0.060872     0.0    0.0  0.060872  0.0   
2    0.049041  0.049041    0.0   0.0  0.091023     0.0    0.0  0.091023  0.0   
3    0.042501  0.042501    0.0   0.0  0.078884     0.0    0.0  0.078884  0.0   
4    0.047074  0.047074    0.0   0.0  0.087371     0.0    0.0  0.087371  0.0   
..        ...       ...    ...   ...       ...     ...    ...       ...  ...   
195  0.093075  0.093075    0.0   0.0  0.086376     0.0    0.0  0.086376  0.0   
196  0.061862  0.061862    0.0   0.0  0.114819     0.0    0.0  0.114819  0.0   
197  0.065908  0.065908    0.0   0.0  0.122329     0.0    0.0  0.122329  0.0   
198  0.060345  0.060345    0.0   0.0  0.112003     0.0    0.0  0.112003  0.0   
199  0.041189  0.041189    0.0   0.0  0.076448     0.0    0.0  0.076448  0.0   

      一定  ...        題材   類別        類型   顯示   顯著  顯著性        風格  風格特徵   驗證  \
0    0.0  ...  0.093386  0.0  0.000000  0.0  0.0  0.0  0.181994   0.0  0.0   
1    0.0  ...  0.078088  0.0  0.000000  0.0  0.0  0.0  0.243490   0.0  0.0   
2    0.0  ...  0.116766  0.0  0.000000  0.0  0.0  0.0  0.182047   0.0  0.0   
3    0.0  ...  0.000000  0.0  0.139258  0.0  0.0  0.0  0.315535   0.0  0.0   
4    0.0  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.305799   0.0  0.0   
..   ...  ...       ...  ...       ...  ...  ...  ...       ...   ...  ...   
195  0.0  ...  0.110805  0.0  0.000000  0.0  0.0  0.0  0.215940   0.0  0.0   
196  0.0  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.172228   0.0  0.0   
197  0.0  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.305822   0.0  0.0   
198  0.0  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.336008   0.0  0.0   
199  0.0  ...  0.000000  0.0  0.000000  0.0  0.0  0.0  0.191121   0.0  0.0   

      點與  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0  
..   ...  
195  0.0  
196  0.0  
197  0.0  
198  0.0  
199  0.0  

[200 rows x 425 columns]

In [216]:
df_word_tfidf.to_csv(("df_word_tfidf.csv"), index=False, encoding="utf-8")

In [235]:
df_word_tfidf.shape

(200, 425)

### cosine_similarity

In [227]:
# 直接看cosine_similarity
similarity_matrix = cosine_similarity(df_word_tfidf)
similarity_matrix

array([[1.        , 0.40648301, 0.52760724, ..., 0.61382774, 0.61963303,
        0.57060203],
       [0.40648301, 1.        , 0.41714523, ..., 0.5354455 , 0.47025997,
        0.41890744],
       [0.52760724, 0.41714523, 1.        , ..., 0.62671804, 0.64903114,
        0.52373883],
       ...,
       [0.61382774, 0.5354455 , 0.62671804, ..., 1.        , 0.83263939,
        0.66816689],
       [0.61963303, 0.47025997, 0.64903114, ..., 0.83263939, 1.        ,
        0.65952652],
       [0.57060203, 0.41890744, 0.52373883, ..., 0.66816689, 0.65952652,
        1.        ]])

In [232]:
output_file = 'cosine_similarity.csv'

# Write the similarity matrix to a CSV file
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write the header row with the document names
    writer.writerow([''] + list(response_df["id"]))
    
    # Write each row of the similarity matrix
    for i, row in enumerate(similarity_matrix):
        writer.writerow([list(response_df["id"])[i]] + list(row))

In [237]:
# Apply SVD: cosine_similarity
k = 10  # Number of components to keep
svd = TruncatedSVD(n_components=k, random_state=42)
svd_matrix = svd.fit_transform(df_word_tfidf)

# Calculate document similarity
similarity_matrix = cosine_similarity(svd_matrix)
print(similarity_matrix)

output_file = 'cosine_similarity_svd_10.csv'

# Write the similarity matrix to a CSV file
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write the header row with the document names
    writer.writerow([''] + list(response_df["id"]))
    
    # Write each row of the similarity matrix
    for i, row in enumerate(similarity_matrix):
        writer.writerow([list(response_df["id"])[i]] + list(row))

[[1.         0.70422127 0.89123062 ... 0.79156828 0.82060242 0.8705868 ]
 [0.70422127 1.         0.67959473 ... 0.78913429 0.68505976 0.71577265]
 [0.89123062 0.67959473 1.         ... 0.83159714 0.88766726 0.83515052]
 ...
 [0.79156828 0.78913429 0.83159714 ... 1.         0.94289    0.84795448]
 [0.82060242 0.68505976 0.88766726 ... 0.94289    1.         0.85032639]
 [0.8705868  0.71577265 0.83515052 ... 0.84795448 0.85032639 1.        ]]


In [238]:
# Apply SVD: cosine_similarity
k = 50  # Number of components to keep
svd = TruncatedSVD(n_components=k, random_state=42)
svd_matrix = svd.fit_transform(df_word_tfidf)

# Calculate document similarity
similarity_matrix = cosine_similarity(svd_matrix)
print(similarity_matrix)

output_file = 'cosine_similarity_svd_50.csv'

# Write the similarity matrix to a CSV file
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write the header row with the document names
    writer.writerow([''] + list(response_df["id"]))
    
    # Write each row of the similarity matrix
    for i, row in enumerate(similarity_matrix):
        writer.writerow([list(response_df["id"])[i]] + list(row))

[[1.         0.49618259 0.63897805 ... 0.72877408 0.71381141 0.6924486 ]
 [0.49618259 1.         0.45315779 ... 0.60068201 0.53484277 0.47006233]
 [0.63897805 0.45315779 1.         ... 0.68209337 0.71428743 0.5950922 ]
 ...
 [0.72877408 0.60068201 0.68209337 ... 1.         0.89197873 0.74015204]
 [0.71381141 0.53484277 0.71428743 ... 0.89197873 1.         0.74243152]
 [0.6924486  0.47006233 0.5950922  ... 0.74015204 0.74243152 1.        ]]


In [239]:
# Apply SVD: cosine_similarity
k = 100  # Number of components to keep
svd = TruncatedSVD(n_components=k, random_state=42)
svd_matrix = svd.fit_transform(df_word_tfidf)

# Calculate document similarity
similarity_matrix = cosine_similarity(svd_matrix)
print(similarity_matrix)

output_file = 'cosine_similarity_svd_100.csv'

# Write the similarity matrix to a CSV file
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write the header row with the document names
    writer.writerow([''] + list(response_df["id"]))
    
    # Write each row of the similarity matrix
    for i, row in enumerate(similarity_matrix):
        writer.writerow([list(response_df["id"])[i]] + list(row))

[[1.         0.42299657 0.54002128 ... 0.63308668 0.64481779 0.59650825]
 [0.42299657 1.         0.43394524 ... 0.55195045 0.48772411 0.43869365]
 [0.54002128 0.43394524 1.         ... 0.64211343 0.67444458 0.54929508]
 ...
 [0.63308668 0.55195045 0.64211343 ... 1.         0.85982213 0.69581208]
 [0.64481779 0.48772411 0.67444458 ... 0.85982213 1.         0.68749759]
 [0.59650825 0.43869365 0.54929508 ... 0.69581208 0.68749759 1.        ]]


In [240]:
# Apply SVD: cosine_similarity
k = 200  # Number of components to keep
svd = TruncatedSVD(n_components=k, random_state=42)
svd_matrix = svd.fit_transform(df_word_tfidf)

# Calculate document similarity
similarity_matrix = cosine_similarity(svd_matrix)
print(similarity_matrix)

output_file = 'cosine_similarity_svd_200.csv'

# Write the similarity matrix to a CSV file
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write the header row with the document names
    writer.writerow([''] + list(response_df["id"]))
    
    # Write each row of the similarity matrix
    for i, row in enumerate(similarity_matrix):
        writer.writerow([list(response_df["id"])[i]] + list(row))

[[1.         0.40648301 0.52760724 ... 0.61382774 0.61963303 0.57060203]
 [0.40648301 1.         0.41714523 ... 0.5354455  0.47025997 0.41890744]
 [0.52760724 0.41714523 1.         ... 0.62671804 0.64903114 0.52373883]
 ...
 [0.61382774 0.5354455  0.62671804 ... 1.         0.83263939 0.66816689]
 [0.61963303 0.47025997 0.64903114 ... 0.83263939 1.         0.65952652]
 [0.57060203 0.41890744 0.52373883 ... 0.66816689 0.65952652 1.        ]]


### euclidean_distances

In [241]:
# 直接看euclidean_distances
similarity_matrix = euclidean_distances(df_word_tfidf)
print(similarity_matrix)

output_file = 'euclidean_distances.csv'

# Write the similarity matrix to a CSV file
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write the header row with the document names
    writer.writerow([''] + list(response_df["id"]))
    
    # Write each row of the similarity matrix
    for i, row in enumerate(similarity_matrix):
        writer.writerow([list(response_df["id"])[i]] + list(row))

[[0.         1.08951089 0.97200078 ... 0.87883134 0.87220063 0.92671244]
 [1.08951089 0.         1.0796803  ... 0.963903   1.02931048 1.0780469 ]
 [0.97200078 1.0796803  0.         ... 0.86403931 0.83781724 0.97597251]
 ...
 [0.87883134 0.963903   0.86403931 ... 0.         0.57855097 0.81465712]
 [0.87220063 1.02931048 0.83781724 ... 0.57855097 0.         0.8251951 ]
 [0.92671244 1.0780469  0.97597251 ... 0.81465712 0.8251951  0.        ]]


In [242]:
# Apply SVD: euclidean_distances
k = 10  # Number of components to keep
svd = TruncatedSVD(n_components=k, random_state=42)
svd_matrix = svd.fit_transform(df_word_tfidf)

# Calculate document similarity
similarity_matrix = euclidean_distances(svd_matrix)
print(similarity_matrix)

output_file = 'euclidean_distances_svd_10.csv'

# Write the similarity matrix to a CSV file
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write the header row with the document names
    writer.writerow([''] + list(response_df["id"]))
    
    # Write each row of the similarity matrix
    for i, row in enumerate(similarity_matrix):
        writer.writerow([list(response_df["id"])[i]] + list(row))

[[0.         0.58958622 0.37069261 ... 0.58073653 0.52098204 0.41998155]
 [0.58958622 0.         0.62045924 ... 0.58262998 0.67284381 0.60746574]
 [0.37069261 0.62045924 0.         ... 0.52694428 0.41850858 0.47561776]
 ...
 [0.58073653 0.58262998 0.52694428 ... 0.         0.31628537 0.504664  ]
 [0.52098204 0.67284381 0.41850858 ... 0.31628537 0.         0.48410781]
 [0.41998155 0.60746574 0.47561776 ... 0.504664   0.48410781 0.        ]]


In [243]:
# Apply SVD: euclidean_distances
k = 50  # Number of components to keep
svd = TruncatedSVD(n_components=k, random_state=42)
svd_matrix = svd.fit_transform(df_word_tfidf)

# Calculate document similarity
similarity_matrix = euclidean_distances(svd_matrix)
print(similarity_matrix)

output_file = 'euclidean_distances_svd_50.csv'

# Write the similarity matrix to a CSV file
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write the header row with the document names
    writer.writerow([''] + list(response_df["id"]))
    
    # Write each row of the similarity matrix
    for i, row in enumerate(similarity_matrix):
        writer.writerow([list(response_df["id"])[i]] + list(row))

[[0.         0.9027713  0.77746779 ... 0.68610089 0.69576208 0.71318243]
 [0.9027713  0.         0.98022246 ... 0.84892688 0.9069246  0.95936232]
 [0.77746779 0.98022246 0.         ... 0.76708212 0.72027466 0.85023185]
 ...
 [0.68610089 0.84892688 0.76708212 ... 0.         0.44859218 0.69015431]
 [0.69576208 0.9069246  0.72027466 ... 0.44859218 0.         0.68023942]
 [0.71318243 0.95936232 0.85023185 ... 0.69015431 0.68023942 0.        ]]


In [244]:
# Apply SVD: euclidean_distances
k = 100  # Number of components to keep
svd = TruncatedSVD(n_components=k, random_state=42)
svd_matrix = svd.fit_transform(df_word_tfidf)

# Calculate document similarity
similarity_matrix = euclidean_distances(svd_matrix)
print(similarity_matrix)

output_file = 'euclidean_distances_svd_100.csv'

# Write the similarity matrix to a CSV file
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write the header row with the document names
    writer.writerow([''] + list(response_df["id"]))
    
    # Write each row of the similarity matrix
    for i, row in enumerate(similarity_matrix):
        writer.writerow([list(response_df["id"])[i]] + list(row))

[[0.         1.0583325  0.94510495 ... 0.84490627 0.83012964 0.87911871]
 [1.0583325  0.         1.04740942 ... 0.93275522 0.99597197 1.03580342]
 [0.94510495 1.04740942 0.         ... 0.83378789 0.7941201  0.92835298]
 ...
 [0.84490627 0.93275522 0.83378789 ... 0.         0.52159743 0.76347966]
 [0.83012964 0.99597197 0.7941201  ... 0.52159743 0.         0.77270577]
 [0.87911871 1.03580342 0.92835298 ... 0.76347966 0.77270577 0.        ]]


In [245]:
# Apply SVD: euclidean_distances
k = 200  # Number of components to keep
svd = TruncatedSVD(n_components=k, random_state=42)
svd_matrix = svd.fit_transform(df_word_tfidf)

# Calculate document similarity
similarity_matrix = euclidean_distances(svd_matrix)
print(similarity_matrix)

output_file = 'euclidean_distances_svd_200.csv'

# Write the similarity matrix to a CSV file
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    # Write the header row with the document names
    writer.writerow([''] + list(response_df["id"]))
    
    # Write each row of the similarity matrix
    for i, row in enumerate(similarity_matrix):
        writer.writerow([list(response_df["id"])[i]] + list(row))

[[0.         1.08951089 0.97200078 ... 0.87883134 0.87220063 0.92671244]
 [1.08951089 0.         1.0796803  ... 0.963903   1.02931048 1.0780469 ]
 [0.97200078 1.0796803  0.         ... 0.86403931 0.83781724 0.97597251]
 ...
 [0.87883134 0.963903   0.86403931 ... 0.         0.57855097 0.81465712]
 [0.87220063 1.02931048 0.83781724 ... 0.57855097 0.         0.8251951 ]
 [0.92671244 1.0780469  0.97597251 ... 0.81465712 0.8251951  0.        ]]


In [54]:
#查看计算的idf（需要？）
df_word_idf = pd.DataFrame(list(zip(vectorizer.get_feature_names(),transformer.idf_)),columns=['单词','idf'])

df_word_idf

单词       idf
0       2012  1.077558
1       2018  1.077558
2      21916  5.610158
3       6943  5.610158
4    jaccard  1.000000
..       ...       ...
460       風格  1.000000
461     風格特徵  4.223863
462       风格  5.204693
463       驗證  4.357395
464       點與  5.610158

[465 rows x 2 columns]

# 分研究動機、目的、方法、結果來觀察

In [74]:
data = []
for j in range(100):
    ans = response_df["response"][j]

    # 將回覆內容分割成不同的部分
    sections = ["研究動機", "研究目的", "研究方法", "研究結果"]
    contents = ans.split("\n\n")  # 以兩個換行符分割回覆內容

    # 逐個部分建立資料
    for section, content in zip(sections, contents):
        # 取得每個部分的句子和內容
        text_list = content.split("\n")[1:]
        num_sentence = len(text_list)
        text = str()
        for i in text_list:
            text = text+i

        # 建立一個字典儲存資料
        section_data = {
            "id": response_df["id"][j],
            "研究部分": section,
            "句數": num_sentence,
            "內容": text,
            "類型": response_df["type"][j]
        }

        data.append(section_data)

# 轉換為DataFrame
df = pd.DataFrame(data)

# 顯示結果
df

id  研究部分  句數                                                 內容     類型
0      1  研究動機   1              - 媒體對同一主題的報導經常有明顯差異，不同報紙的報導風格是否有明顯差異？  point
1      1  研究目的   3  - 比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格，以報紙報導...  point
2      1  研究方法   3  - 文字分析法：從詞彙、句長、標點、虛字等角度進行分析。- 統計分析法：將四大報頭條標題及內...  point
3      1  研究結果   2  - 四大報頭條標題及內文的用字風格不完全相同，其中標題的Jaccard指標將同時期報導放在同...  point
4      2  研究動機   1                - 媒體對同一主題的報導經常有明顯差異，本研究探討報紙報導風格之差異。  point
..   ...   ...  ..                                                ...    ...
395   99  研究結果   3  - 四大報頭條標題及內文的用字風格不完全相同，但Jaccard指標將同時期報導放在同一群，Y...  point
396  100  研究動機   1                        - 想瞭解媒體報導風格的差異，並從中找出報紙之間的異同  point
397  100  研究目的   3  - 比較臺灣四大報《蘋果日報》、《自由時報》、《聯合報》、《中國時報》的報導風格- 避免報紙...  point
398  100  研究方法   4  - 蒐集2012年至2018年間四大報頭版頭條新聞作為研究資料- 分析常用詞彙、句長、標點、...  point
399  100  研究結果   3  - 四大報頭條標題及內文的用字風格不完全相同，其中標題的Jaccard指標將同時期報導放在同...  point

[400 rows x 5 columns]